services:
  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=supersecret
      - DOCKER_INFLUXDB_INIT_ORG=Workshop
      - DOCKER_INFLUXDB_INIT_BUCKET=AirQuality
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=AirQualityToken
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:11.2.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge

volumes:
  influxdb_data:
  grafana_data: